#!/usr/bin/env bash

_writeEmptyJsonIfFileDoesNotExist() {
  local filePath="$1"

	if [[ ! -f "$filePath" ]]; then
		echo "{}" > "$filePath"
	fi
}

toJsonArray() {
  local inputArray=("$@")

  if [[ ${#inputArray[@]} -eq 0 ]]; then
    echo "[]"
    return
  fi

  jq -Rn --argjson args "$(printf '%s\n' "${inputArray[@]}" | jq -R . | jq -s .)" '$args'
}

toJsonString() {
  echo "\"$1\""
}

writeJsonField() {
  local filePath="$1"
  local fieldName="$2"
  local value="$3"

  _writeEmptyJsonIfFileDoesNotExist "$filePath"

  local temp_file="$filePath.tmp"

  jq --argjson value "$value" ". += {\"$fieldName\": \$value}" "$filePath" > "$temp_file" \
    && mv "$temp_file" "$filePath"
}