#!/usr/bin/env bash

bats_load_library "fileAssertions"
bats_load_library "commandWriter"
bats_load_library "common"

_runCommandLocation() {
  echo "$(testEnvDir)/run"
}

writeSpyRunCommand() {
	local commandName="$1"

  writeSpyCommand "$(_runCommandLocation)" "$commandName"
}

assert_run_command_was_executed() {
	local commandName="$1"
	local content="$2"

	assert_spy_file_has_content "$(_runCommandLocation)/$commandName/$(commandFileName)" "$content"
}

writeStubRunCommand() {
	local commandName="$1"
	local exitCode="$2"
	local output="$3"

  writeStubCommand "$(_runCommandLocation)" "$commandName" "$exitCode" "$output"
}

writeStdErrRunCommand() {
	local commandName="$1"
	local error="$2"

	writeStdErrScript "$(_runCommandLocation)/$commandName/$(commandFileName)" "$error"
}

writeRunCommandRequestingInput() {
	local commandName="$1"

	writeCommandRequestingInput "$(_runCommandLocation)" "$commandName"
}

assert_run_command_received_input() {
	local commandName="$1"
	local input="$2"

	assert_command_received_input "$(_runCommandLocation)" "$commandName" "$input"
}