#!/usr/bin/env bash

bats_load_library "fileAssertions"
bats_load_library "scriptFactory"

writeScript() {
  local content="$1"
  local scriptPath="$2"

	mkdir -p "$(dirname "$scriptPath")"

  echo "$content" > "$scriptPath"
  chmod +x "$scriptPath"
}

writeSpyScript() {
	local scriptPath="$1"

  local commandName
  commandName="$(basename "$scriptPath")"

  local content
  content="$(makeSpyScript "$commandName")"

	writeScript "$content" "$scriptPath"
}

writeStubScript() {
	local scriptPath="$1"
	local exitCode="$2"
	local output="$3"

  local content
  content="$(makeStubScript "$output" "$exitCode")"

  writeScript "$content" "$scriptPath"
}

writeScriptRequestingInput() {
	local scriptPath=$1

  local content
  content="$(makeScriptRequestingInput)"

  writeScript "$content" "$scriptPath"
}

writeStdErrScript() {
	local scriptPath=$1
	local errorMessage=$2

	local content
	content="$(makeStdErrScript "$errorMessage")"

	writeScript "$content" "$scriptPath"
}

assert_spy_file_has_content() {
	spyFile=$1$(spyFileSuffix)
	expectedContent=$2

	actualContent="$(cat "$spyFile")"

	assert_equal "$actualContent" "$expectedContent"
}

assert_spy_file_exists() {
	assert_file_exists "$1$(spyFileSuffix)"
}

assert_spy_file_does_not_exist() {
	assert_file_does_not_exist "$1$(spyFileSuffix)"
}
