#!/usr/bin/env bash

bats_load_library "fileAssertions"
bats_load_library "commandWriter"
bats_load_library "common"

_setupCommandLocation() {
  echo "$(testEnvDir)/setup"
}

writeSpySetupCommand() {
	local commandName="$1"

  writeSpyCommand "$(_setupCommandLocation)" "$commandName"
}

assert_setup_command_was_executed() {
	local commandName="$1"
	local expectedParameters="$2"

	assert_script_was_executed_with_parameters "$(_setupCommandLocation)/$commandName/$(commandFileName)" "$expectedParameters"
}

assert_setup_command_was_not_executed() {
	local commandName="$1"

	assert_spy_file_does_not_exist "$(_setupCommandLocation)/$commandName/$(commandFileName)"
}

writeStubSetupCommand() {
	local commandName="$1"
	local exitCode="$2"
	local output="$3"

  writeStubCommand "$(_setupCommandLocation)" "$commandName" "$exitCode" "$output"
}

writeStdErrSetupCommand() {
	local commandName="$1"
	local error="$2"

	writeStdErrCommand "$(_setupCommandLocation)" "$commandName" "$error"
}

writeSetupCommandRequestingInput() {
	local commandName="$1"

	writeCommandRequestingInput "$(_setupCommandLocation)" "$commandName"
}

assert_setup_command_received_input() {
	local commandName="$1"
	local input="$2"

	assert_command_received_input "$(_setupCommandLocation)" "$commandName" "$input"
}