#!/usr/bin/env bash
set -e

bats_load_library "fixtures/authenticated_fixture"
bats_load_library "setup"
bats_load_library "git"
bats_load_library "repositoriesPath"

repository="1_TestRepository"

setup() {
	authenticated_setup

	cloneTestingRepositories "$(testEnvDir)/$(default_repositories_path)" "$repository"
	setupGitHooks
}

teardown() {
	authenticated_teardown
}

repositoryDir() {
	echo "$(testEnvDir)/$(default_repositories_path)/$repository"
}
