#!/usr/bin/env bash
set -e

bats_load_library "ssh-authenticate"
bats_load_library "common_fixture"
bats_load_library "setup"
bats_load_library "git"
bats_load_library "repositoriesPath"

repository="1_TestRepository"

setup() {
	common_setup
	authenticate

	cloneTestingRepositories "$(testEnvDir)/$(default_repositories_path)" "$repository"
	setupGitHooks
}

teardown() {
	revoke-authentication
	common_teardown
}

repositoryDir() {
	echo "$(testEnvDir)/$(default_repositories_path)/$repository"
}
