#!/usr/bin/env bash

_teamFileName() {
	echo "team.json"
}

_teamFilePath() {
  echo "$(testEnvDir)/$(_teamFileName)"
}

_createTeamFileIfNotExisting() {
	if [[ ! -f "$(_teamFilePath)" ]]; then
		echo "{}" > "$(_teamFilePath)"
	fi
}

_toJsonArray() {
  local inputArray=("$@")

  if [[ ${#inputArray[@]} -eq 0 ]]; then
    echo "[]"
    return
  fi

  jq -Rn --argjson args "$(printf '%s\n' "${inputArray[@]}" | jq -R . | jq -s .)" '$args'
}

_toJsonString() {
  echo "\"$1\""
}

_updateJsonField() {
  local fieldName="$1"
  local value="$2"

  _createTeamFileIfNotExisting

  local temp_file
  temp_file="$(_teamFilePath).tmp"

  jq --argjson value "$value" ". += {\"$fieldName\": \$value}" "$(_teamFilePath)" > "$temp_file" \
    && mv "$temp_file" "$(_teamFilePath)"
}

writeBlockedBranches() {
	_updateJsonField "blockedBranches" "$(_toJsonArray "$@")"
}

writeRepositoriesPrefixes() {
	_updateJsonField "repositoriesPrefixes" "$(_toJsonArray "$@")"
}

writeRepositoriesUrls() {
	_updateJsonField "repositories" "$(_toJsonArray "$@")"
}

writeRepositoriesPath() {
  _updateJsonField "repositoriesPath" "$(_toJsonString "$1")"
}

writeCommitPrefixRegex() {
  _updateJsonField "commitPrefixRegex" "$(_toJsonString "$1")"
}