#!/usr/bin/env bash

bats_load_library "jsonWriter"

_teamFileName() {
	echo "team.json"
}

_teamFilePath() {
  echo "$(testEnvDir)/$(_teamFileName)"
}


_writeToTeamFile() {
  writeJsonField "$(_teamFilePath)" "$1" "$2"
}

writeBlockedBranches() {
	_writeToTeamFile "blockedBranches" "$(toJsonArray "$@")"
}

writeRepositoriesPrefixes() {
	_writeToTeamFile "repositoriesPrefixes" "$(toJsonArray "$@")"
}

writeRepositoriesUrls() {
	_writeToTeamFile "repositories" "$(toJsonArray "$@")"
}

writeRepositoriesPath() {
  _writeToTeamFile "repositoriesPath" "$(toJsonString "$1")"
}

writeCommitPrefixRegex() {
  _writeToTeamFile "commitPrefixRegex" "$(toJsonString "$1")"
}