#!/bin/bash

assert_directory_exists() {
  actual=$1

  if [ ! -d "$actual" ]
  then
    echo "The directory $actual does not exists, but is was expected to exist."
    exit 1
  fi
}

assert_directories_exists() {
  directories=($*)

  for dir in "${directories[@]}"
  do

    assert_directory_exists "$dir"
  done
}