#!/bin/bash

cloneTestingRepositories() {
  repositoryDir=$1
  shift
  repositoriesToClone=("$@")

  for repositoryToClone in "${repositoriesToClone[@]}"
  do
    git clone "$(getTestingRepositoryUrl "$repositoryToClone")" "$repositoryDir/$repositoryToClone"
  done
}