#!/bin/bash

_testEnvDir() {
  echo "./testEnv/$(uuidgen)"
}

_common_setup() {
  load '3rdParty/test_helper/bats-support/load'
  load '3rdParty/test_helper/bats-assert/load'

  testEnvironmentDir=$(_testEnvDir)

  PROJECT_ROOT="$( cd "$( dirname "$BATS_TEST_FILENAME" )/.." >/dev/null 2>&1 && pwd )"
  BIN_PATH="$PROJECT_ROOT/build"
  BIN_NAME="mrt"

  mkdir -p "$testEnvironmentDir"
  cp "$BIN_PATH/$BIN_NAME" "$testEnvironmentDir"/$BIN_NAME

  eval "$(ssh-agent -s 3>&-)"
}

_common_teardown() {
  rm -rf "$testEnvironmentDir"
  eval "$(ssh-agent -k)"
}