#!/bin/bash

HELPER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

_common_setup() {
  load "$HELPER_DIR/../3rdParty/test_helper/bats-support/load"
  load "$HELPER_DIR/../3rdParty/test_helper/bats-assert/load"
  load "$HELPER_DIR/absolutePath"

  local projectRoot
  projectRoot=$(pwd)

  testEnvDir="testEnv/$(uuidgen)"
  testEnvBinDir="$testEnvDir/bin"
  exeName="mrt-bin"
  
  mkdir -p "$testEnvBinDir"
  local pathToBinary
  pathToBinary="$(mrt --team-dir "$projectRoot" run binary-location)"
  cp "$pathToBinary" "$testEnvBinDir/$exeName"

  chmod +x "$testEnvBinDir/$exeName"

  PATH="$PATH:$(absolutePath "$testEnvBinDir")"

  eval "$(ssh-agent -s 3>&-)"
}

_common_teardown() {
  rm -rf "$testEnvDir"
  eval "$(ssh-agent -k)"
}