#!/bin/bash

commit_changes() {
  repository_path=$1
  branch_name=$2
  commit_message=${3:-"Some Commit"}

  git -C "$repository_path" checkout -b "$branch_name"
  touch "$repository_path"/some_file
  git -C "$repository_path" add .
  git -C "$repository_path" commit -m "$commit_message"
}

commit_changes_bypassing_githooks() {
  repository_path=$1
  branch_name=$2

  git -C "$repository_path" checkout -b "$branch_name"
  touch "$repository_path"/some_file
  git -C "$repository_path" add .
  git -C "$repository_path" commit -m "Some Commit" --no-verify
}

get_commit_message_of_last_commit() {
  repository_path=$1

  git -C "$repository_path" log -1 --pretty=%B
}