#!/usr/bin/env bash

_testEnvDir="testEnv/$(uuidgen)"
_exeName="mrt-bin"

_common_setup() {
  local HELPER_DIR
  HELPER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
	load "$HELPER_DIR/../3rdParty/test_helper/bats-support/load"
	load "$HELPER_DIR/../3rdParty/test_helper/bats-assert/load"
	load "$HELPER_DIR/absolutePath"

	local projectRoot
	projectRoot=$(pwd)

	local testEnvBinDir
	testEnvBinDir="$_testEnvDir/bin"

	mkdir -p "$testEnvBinDir"
	local pathToBinary
	pathToBinary="$(mrt --team-dir "$projectRoot" run binary-location)"
	cp "$pathToBinary" "$testEnvBinDir/$_exeName"

	chmod +x "$testEnvBinDir/$_exeName"

	PATH="$PATH:$(absolutePath "$testEnvBinDir")"

	eval "$(ssh-agent -s 3>&-)"
}

_common_teardown() {
	rm -rf "$_testEnvDir"
	eval "$(ssh-agent -k)"
}

execute() {
	"$_exeName" --team-dir "$_testEnvDir" "$@"
}

runCommand() {
	execute run "$@"
}