#!/bin/bash

assert_file_does_not_exist() {
  actual=$1

  if [ -f "$actual" ]
  then
    echo "The file $actual exists, but is was expected to not exist."
    exit 1
  fi
}

assert_file_exists() {
  actual=$1

  if [ ! -f "$actual" ]
  then
    echo "The file $actual does not exists, but is was expected to exist."
    exit 1
  fi
}