#!/bin/bash

load 'helpers/writeTeamFile'
load 'helpers/runMrtInTestEnvironment'

setupAll() {
  readarray -t repositoriesUrls < <(getRepositoryUrls "$@")
  setupAllUrls "${repositoriesUrls[@]}"
}

setupAllUrls() {
  writeRepositoriesUrls "$@"

  mrt setup all
}

setupClone() {
  readarray -t repositoriesUrls < <(getRepositoryUrls "$@")
  setupCloneUrls "${repositoriesUrls[@]}"
}

setupCloneUrls() {
  writeRepositoriesUrls "$@"

  mrt setup clone-repositories
}