#!/bin/bash

load 'helpers/writeTeamFile'
load 'helpers/runMrtInTestEnvironment'

setupAll() {
  writeRepositoriesUrls "$@"

  mrt setup all
}

setupCloneRepositories() {
  readarray -t repositoriesUrls < <(getRepositoryUrls "$@")
  writeRepositoriesUrls "${repositoriesUrls[@]}"

  mrt setup clone-repositories
}