#!/bin/bash -e

HELPER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

load "$HELPER_DIR/ssh-authenticate"
load "$HELPER_DIR/common"
load "$HELPER_DIR/setup"
load "$HELPER_DIR/git"
load "$HELPER_DIR/repositoriesPath"

repository="1_TestRepository"

setup() {
  _common_setup
  authenticate

  cloneTestingRepositories "$testEnvDir/$(default_repositories_path)" "$repository"
  setupGitHooks
}

teardown() {
  revoke-authentication
  _common_teardown
}

repositoryDir() {
  echo "$testEnvDir/$(default_repositories_path)/$repository"
}