#!/bin/bash

teamFileName() {
  echo "team.json"
}

getTestingRepositoryUrl() {
  repositoryName=$1

  echo "git@github-testing:janisZisenisTesting/$repositoryName.git"
}

getRepositoryUrls() {
  repositoryNames=($*)

  for r in "${repositoryNames[@]}"
  do
    getTestingRepositoryUrl "$r"
  done
}

writeBlockedBranches() {
  blockedBranches=($*)

  createTeamFileIfNotExisting

  concatenation=""
  for b in "${blockedBranches[@]}"
  do
    concatenation="$concatenation\"$b\","
  done

  if [[ ${#blockedBranches[*]} -gt 0 ]]
  then
    concatenation=${concatenation::-1}
  fi

  jsonArray="[$concatenation]"

  string=$(jq --argjson jsonArray "$jsonArray" '. += {"blockedBranches": ($jsonArray)}' "$testEnvironmentDir/$(teamFileName)")
  echo "$string" > "$testEnvironmentDir/$(teamFileName)"
}

writeRepositories() {
  repositories=($*)

  createTeamFileIfNotExisting

  repositoryUrls=""
  for r in "${repositories[@]}"
  do
  repositoryUrls="$repositoryUrls\"$r\","
  done

  if [[ ${#repositories[*]} -gt 0 ]]
  then
    repositoryUrls=${repositoryUrls::-1}
  fi

  jsonArray="[$repositoryUrls]"

  string=$(jq --argjson jsonArray "$jsonArray" '. += {"repositories": ($jsonArray)}' "$testEnvironmentDir/$(teamFileName)")
  echo "$string" > "$testEnvironmentDir/$(teamFileName)"
}

writeRepositoriesPrefixes() {
  repositoriesPrefixes=($*)

  createTeamFileIfNotExisting

  concatenation=""
  for p in "${repositoriesPrefixes[@]}"
  do
    concatenation="$concatenation\"$p\","
  done

  if [[ ${#repositoriesPrefixes[*]} -gt 0 ]]
  then
    concatenation=${concatenation::-1}
  fi

  jsonArray="[$concatenation]"

  string=$(jq --argjson jsonArray "$jsonArray" '. += {"repositoriesPrefixes": ($jsonArray)}' "$testEnvironmentDir/$(teamFileName)")
  echo "$string" > "$testEnvironmentDir/$(teamFileName)"
}

writeRepositoriesPath() {
  repositoriesPath=$1

  createTeamFileIfNotExisting

  string=$(jq --arg repositoriesPath "$repositoriesPath" '. += {"repositoriesPath": ($repositoriesPath)}' "$testEnvironmentDir/$(teamFileName)")
  echo "$string" > "$testEnvironmentDir/$(teamFileName)"
}

writeCommitPrefixRegex() {
  prefix=$1

  createTeamFileIfNotExisting

  string=$(jq --arg prefix "$prefix" '. += {"commitPrefixRegex": ($prefix)}' "$testEnvironmentDir/$(teamFileName)")
  echo "$string" > "$testEnvironmentDir/$(teamFileName)"
}

createTeamFileIfNotExisting() {
  if [[ ! -f "$testEnvironmentDir/$(teamFileName)" ]]
  then
      echo "{}" > "$testEnvironmentDir/$(teamFileName)"
  fi
}
