#!/bin/bash

teamFileName() {
  echo "team.json"
}

getTestingRepositoryUrl() {
  repositoryName=$1

  echo "git@github-testing:janisZisenisTesting/$repositoryName.git"
}

writeBlockedBranches() {
  testEnvDir=$1
  shift
  blockedBranches=($*)

  createTeamFileIfNotExisting "$testEnvDir"

  concatenation=""
  for b in "${blockedBranches[@]}"
  do
    concatenation="$concatenation\"$b\","
  done

  if [[ ${#blockedBranches[*]} -gt 0 ]]
  then
    concatenation=${concatenation::-1}
  fi

  jsonArray="[$concatenation]"

  string=$(jq --argjson jsonArray "$jsonArray" '. += {"blockedBranches": ($jsonArray)}' "$testEnvDir/$(teamFileName)")
  echo "$string" > "$testEnvDir/$(teamFileName)"
}

writeRepositories() {
  testEnvDir=$1
  shift
  repositories=($*)

  createTeamFileIfNotExisting "$testEnvDir"

  repositoryUrls=""
  for r in "${repositories[@]}"
  do
  repositoryUrls="$repositoryUrls\"$r\","
  done

  if [[ ${#repositories[*]} -gt 0 ]]
  then
    repositoryUrls=${repositoryUrls::-1}
  fi

  jsonArray="[$repositoryUrls]"

  string=$(jq --argjson jsonArray "$jsonArray" '. += {"repositories": ($jsonArray)}' "$testEnvDir/$(teamFileName)")
  echo "$string" > "$testEnvDir/$(teamFileName)"
}

writeRepositoriesPrefixes() {
  testEnvDir=$1
  shift
  repositoriesPrefixes=($*)

  createTeamFileIfNotExisting "$testEnvDir"

  concatenation=""
  for p in "${repositoriesPrefixes[@]}"
  do
    concatenation="$concatenation\"$p\","
  done

  if [[ ${#repositoriesPrefixes[*]} -gt 0 ]]
  then
    concatenation=${concatenation::-1}
  fi

  jsonArray="[$concatenation]"

  string=$(jq --argjson jsonArray "$jsonArray" '. += {"repositoriesPrefixes": ($jsonArray)}' "$testEnvDir/$(teamFileName)")
  echo "$string" > "$testEnvDir/$(teamFileName)"
}

writeRepositoriesPath() {
  testEnvDir=$1
  repositoriesPath=$2

  createTeamFileIfNotExisting "$testEnvDir"

  string=$(jq --arg repositoriesPath "$repositoriesPath" '. += {"repositoriesPath": ($repositoriesPath)}' "$testEnvDir/$(teamFileName)")
  echo "$string" > "$testEnvDir/$(teamFileName)"
}

writeCommitPrefixRegex() {
  testEnvDir=$1
  prefix=$2

  createTeamFileIfNotExisting "$testEnvDir"

  string=$(jq --arg prefix "$prefix" '. += {"commitPrefixRegex": ($prefix)}' "$testEnvDir/$(teamFileName)")
  echo "$string" > "$testEnvDir/$(teamFileName)"
}

createTeamFileIfNotExisting() {
  testEnvDir=$1

  if [[ ! -f "$testEnvDir/$(teamFileName)" ]]
  then
      echo "{}" > "$testEnvDir/$(teamFileName)"
  fi
}
