#!/usr/bin/env bash

set -e

rootDir=$1
shift

readarray -t supportedPlatforms < <(mrt --team-dir "$rootDir" run detect-platform -- --supported-platforms)

mrt --team-dir "$rootDir" run build -- "${supportedPlatforms[@]}"
