name: 'Upload binaries'
description: 'Upload binaries to the specified url'
inputs:
  platform:
    description: 'Platform'
    required: true
  upload-url:
    description: 'Upload url to the release'
    required: true
  github-token:
    description: 'GitHub token to upload the binaries'
    required: true
runs:
  using: 'composite'
  steps:
    - id: download-binaries-variables
      uses: ./.github/actions/download-binaries
      with:
        platform: ${{ inputs.platform }}
    - name: Echo variables
      shell: bash
      run: |
        echo "path: ${{ steps.download-binaries-variables.outputs.binary-path }}"
        echo "name: ${{ steps.download-binaries-variables.outputs.binary-name }}"
    - name: Upload binaries to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        upload_url: ${{ inputs.upload-url }}
        asset_path: ${{ steps.download-binaries-variables.outputs.binary-path }}/${{ steps.download-binaries-variables.outputs.binary-name }}
        asset_name: ${{ steps.download-binaries-variables.outputs.binary-name }}
        asset_content_type: application/octet-stream