name: 'Upload binaries'
description: 'Upload binaries to the specified url'
inputs:
  platform:
    description: 'Platform'
    required: true
  upload-release:
    description: 'Upload url to the release'
    required: true
  github-token:
    description: 'GitHub token to upload the binaries'
    required: true
runs:
  using: 'composite'
  steps:
    - id: set-binary-variables
      uses: ./.github/actions/download-binaries
      with:
        platform: ${{ inputs.platform }}
    - name: Upload binaries to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        upload_url: ${{ inputs.upload-url }}
        asset_path: ${{ inputs.binary-path }}/${{ inputs.binary-name }}
        asset_name: ${{ inputs.binary-name }}
        asset_content_type: application/octet-stream