#!/usr/bin/env bash
set -e

rootDir="$1"
shift

cd "$rootDir/app"
golangci-lint run --config "$rootDir"/.golangci.yml --timeout 10m

cd "$rootDir/go-e2e"
golangci-lint run --config "$rootDir"/.golangci.yml --timeout 10m
