#!/usr/bin/env bash
set -e

rootDir="$1"

function lint_module() {
	local dir="$1"
	cd "$dir"
	golangci-lint run --config "$rootDir"/.golangci.yml --timeout 10m
	go vet ./...
}

lint_module "$rootDir/app"
lint_module "$rootDir/e2e-tests"
