#!/usr/bin/env bash
set -e

FLAG_LOCAL="--local"
FLAG_REMOTE="--remote"
FLAG_CLEAN="--clean"
FLAG_HELP="-h|--help"

declare -A HOSTNAME_MAP=(
	["$FLAG_LOCAL"]="localhost"
	["$FLAG_REMOTE"]="github.com"
)

function display_help() {
	cat <<EOF
Usage: mrt run $(basename "$(dirname "$0")") [OPTIONS]

Run end-to-end tests with various options.

Options:
  $FLAG_LOCAL|$FLAG_REMOTE   Use the local gitlab or github.com to run e2e-tests (default: remote).
  $FLAG_CLEAN                Perform a clean build before running the tests.
  $FLAG_HELP                 Display this help message and exit.
EOF
}

rootDir="$1"
shift
clean_build=false
hostname="${HOSTNAME_MAP[$FLAG_REMOTE]}"

while [[ $# -gt 0 ]]; do
	case "$1" in
	"$FLAG_LOCAL" | "$FLAG_REMOTE")
		hostname="${HOSTNAME_MAP[$1]}"
		shift
		;;
	"$FLAG_CLEAN")
		clean_build=true
		shift
		;;
	"$FLAG_HELP")
		display_help
		exit 0
		;;
	--*)
		echo "Error: Unknown option '$1'."
		echo
		display_help
		exit 1
		;;
	esac
done

SSH_CONFIG_FILE="$rootDir/.ssh/config"
PRIVATE_KEY_FILE="$rootDir/.ssh/private-key"
HOST_ALIAS="github-testing"

if [[ ! -f "$PRIVATE_KEY_FILE" ]]; then
	echo "Error: Private key file not found at $PRIVATE_KEY_FILE"
	exit 1
fi

mkdir -p "$(dirname "$SSH_CONFIG_FILE")"
# Normally you would add "User git" to the config. But somehow this does not work on the ci. There I have to remove
# the user from the config.
if [[ "$hostname" == "localhost" ]]; then
	cat <<EOF >"$SSH_CONFIG_FILE"
Host $HOST_ALIAS
   HostName $hostname
   StrictHostKeyChecking no
   UserKnownHostsFile /dev/null
   LogLevel ERROR
EOF
else
	cat <<EOF >"$SSH_CONFIG_FILE"
Host $HOST_ALIAS
   HostName $hostname
   StrictHostKeyChecking accept-new
   LogLevel ERROR
EOF
fi

if [[ "$clean_build" == true ]]; then
	echo "Performing a clean build for e2e-tests..."
	mrt --team-dir "$rootDir" run build
fi

echo "Running Go e2e tests..."
(cd "$rootDir/go-e2e" && gotestsum --format testname ./... -- -v)