#!/usr/bin/env bash
set -e

rootDir="$1"

function format_module() {
	local dir="$1"
	cd "$dir"
	golangci-lint fmt --config "$rootDir"/.golangci.yml
}

format_module "$rootDir/app"
format_module "$rootDir/e2e-tests"
