#!/usr/bin/env bash

set -e

rootDir=$1
shift

supportedPlatforms=(
  "linux/amd64"
  "linux/arm64"
  "darwin/amd64"
  "darwin/arm64"
  "windows/amd64"
  "windows/386"
)

json='{"platform": []}'

for platform in "${supportedPlatforms[@]}"; do
  platform_data=$(jq -n --arg name "$platform" \
    --arg path "$(mrt --team-dir $rootDir run binary-location -- --dir $platform)" \
    --arg binary_name "$(mrt --team-dir $rootDir run binary-location -- --exe-name $platform)" \
    '{name: $name, "binary-path": $path, "binary-name": $binary_name}')
    
  json=$(echo "$json" | jq --argjson platform_data "$platform_data" '.platform += [$platform_data]')
done

echo "$json" | jq -c .