#!/usr/bin/env bash

bats_load_library "scripts/scriptFactory"

writeScript() {
  local content="$1"
  local scriptPath="$2"

	mkdir -p "$(dirname "$scriptPath")"

  echo "$content" > "$scriptPath"
  chmod +x "$scriptPath"
}

writeStubScript() {
	local scriptPath="$1"
	local exitCode="$2"
	local output="$3"

  writeScript "$(makeStubScript "$output" "$exitCode")" "$scriptPath"
}

writeSpyScript() {
	local scriptPath="$1"

  local commandName
  commandName="$(basename "$scriptPath")"

  local content
  content="$(makeSpyScript "$commandName")"

	writeScript "$content" "$scriptPath"
}

assert_script_was_executed_with_parameters() {
	local scriptPath="$1"
	local expectedParameters="$2"

  assert_script_was_executed "$1"

	assert_equal "$(cat "$scriptPath$(spyFileSuffix)")" "$expectedParameters"
}

assert_script_was_executed() {
	assert_file_exist "$1$(spyFileSuffix)"
}

assert_script_was_not_executed() {
	assert_file_not_exist "$1$(spyFileSuffix)"
}

writeScriptRequestingInput() {
	local scriptPath=$1

  writeScript "$(makeScriptRequestingInput)" "$scriptPath"
}

assert_script_received_input() {
  local scriptPath="$1"
  local expectedInput="$2"

	assert_file_exist "$(dirname "$scriptPath")/$expectedInput"
}

writeStdErrScript() {
	local scriptPath=$1
	local errorMessage=$2

	writeScript "$(makeStdErrScript "$errorMessage")" "$scriptPath"
}