#!/usr/bin/env bash
set -e

FLAG_START="--start"
FLAG_STOP="--stop"
FLAG_HELP="-h|--help"

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

rootDir="$1"
shift
export TEST_REPO_DIR="$rootDir/test-repos"

function display_help() {
	cat <<EOF
Usage: mrt run $(basename "$(dirname "$0")") [OPTIONS]

Manage local GitLab instance with Docker Compose.

Options:
  $FLAG_START|$FLAG_STOP    Start/Stop the local GitLab instance (default: $FLAG_START).
  $FLAG_HELP                Display this help message and exit.
EOF
}


action="$FLAG_START"
while [[ $# -gt 0 ]]; do
	case "$1" in
	"$FLAG_START"|"$FLAG_STOP")
		action="$1"
		shift
		;;
	"$FLAG_HELP")
		display_help
		exit 0
		;;
	--*)
		echo "Error: Unknown option '$1'."
		echo
		display_help
		exit 1
		;;
	*)
		echo "Error: Unknown argument '$1'."
		echo
		display_help
		exit 1
		;;
	esac
done

cmd="docker-compose -f "$SCRIPT_DIR/docker-compose.yml""

if [[ "$action" == "$FLAG_START" ]]; then
	cmd+=" up -d"
elif [[ "$action" == "$FLAG_STOP" ]]; then
  cmd+=" down -v"
fi

eval "$cmd"