#!/usr/bin/env bash
set -e

FLAG_START="--start"
FLAG_STOP="--stop"
FLAG_DUMP_REPOS_FLAG="--dump-repos"
FLAG_HELP_SHORT="-h"
FLAG_HELP_LONG="--help"

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

rootDir="$1"
shift
export TEST_REPO_DIR="$rootDir/test-repos"

function display_help() {
	cat <<EOF
Usage: mrt run $(basename "$(dirname "$0")") [OPTIONS]

Manage local GitLab instance with Docker Compose.

Options:
  $FLAG_START|$FLAG_STOP      Start/Stop the local GitLab instance (default: $FLAG_START).
  $FLAG_DUMP_REPOS_FLAG     Dumps the test repositories when starting the instance. (default: false)
  $FLAG_HELP_SHORT|$FLAG_HELP_LONG           Display this help message and exit.
EOF
}

function dump_repositories() {
  GITHUB_OWNER="janisZisenisTesting"
  TEST_REPO_DIR="$SCRIPT_DIR/test-repos"

  echo "Deleting existing test repositories directory..."
  rm -rf "$SCRIPT_DIR/test-repos"

  if ! gh auth status &> /dev/null; then
      echo "Please log in using 'gh auth login'."
      exit 1
  fi

  REPOS=$(gh repo list $GITHUB_OWNER --limit 1000 --json nameWithOwner -q '.[] | .nameWithOwner')
  [ -z "$REPOS" ] && { echo "No repositories found."; exit 1; }

  rm -rf "$TEST_REPO_DIR"

  for REPO in $REPOS; do
      REPO=$(echo "$REPO" | tr -d '"')
      TARGET_DIR="$TEST_REPO_DIR/$REPO.git"
      mkdir -p "$(dirname "$TARGET_DIR")"
      gh repo clone "$REPO" "$TARGET_DIR" -- --bare
  done

  echo "Cloning completed! Repositories are stored as bare repositories in '$TEST_REPO_DIR'."
}

action="$FLAG_START"
should_dump_repositories=false

while [[ $# -gt 0 ]]; do
	case "$1" in
	"$FLAG_HELP_SHORT"|"$FLAG_HELP_LONG")
	  display_help
	  exit 0
		shift
		;;
	"$FLAG_START"|"$FLAG_STOP")
		action="$1"
		shift
		;;
	"$FLAG_DUMP_REPOS_FLAG")
		should_dump_repositories=true
		shift
		;;
	--*)
		echo "Error: Unknown option '$1'."
		echo
		display_help
		exit 1
		;;
	*)
		echo "Error: Unknown argument '$1'."
		echo
		display_help
		exit 1
		;;
	esac
done

cmd="docker-compose -f \"$SCRIPT_DIR/docker-compose.yml\""

if [[ "$action" == "$FLAG_START" ]]; then
  if [[ "$should_dump_repositories" == true ]]; then
    dump_repositories
  fi
	cmd+=" up -d"
elif [[ "$action" == "$FLAG_STOP" ]]; then
  cmd+=" down -v"
fi

eval "$cmd"