#!/bin/sh

assert_array_equals() {
  actual=$1
  expected=$2

  actualOneLine=$(printf 'actual:\t%s\n' "${actual[*]}" | paste -sd ' ' -)
  expectedOneLine=$(printf 'actual:\t%s\n' "${expected[*]}" | paste -sd ' ' -)

  if [ "$expectedOneLine" != "$actualOneLine" ]
  then
    printf 'actual:\t%s\n' "$actualOneLine" | paste -sd ' ' -
    printf 'expected:\t%s\n' "$expectedOneLine" | paste -sd ' ' -
    exit 1
  fi
}

