#!/usr/bin/env bash

assert_directory_exists() {
    dir=$1

    if [[ -z $dir ]]; then
      echo "You have to pass a directory as parameter"
      exit 1
    fi

    if [ ! -d "$dir" ]; then
        echo "Directory ($dir) does not exist"
        exit 1
    fi
}