#!/usr/bin/env bash

_common_setup() {
  load 'test_helper/bats-support/load'
  load 'test_helper/bats-assert/load'

  testEnvironmentDir=$1

  PROJECT_ROOT="$( cd "$( dirname "$BATS_TEST_FILENAME" )/.." >/dev/null 2>&1 && pwd )"
  BIN_PATH="$PROJECT_ROOT/build"
  BIN_NAME="mrt"

  mkdir -p "$testEnvironmentDir"
  cp "$BIN_PATH/$BIN_NAME" "$testEnvironmentDir"/$BIN_NAME
}

_common_teardown() {
  testEnvironmentDir=$1

  rm -rf "$testEnvironmentDir"
}