#!/bin/bash

push_changes() {
  repository_path=$1
  branch_name=$2

  run git -C "$repository_path" push --set-upstream origin "$branch_name"

  if [[ $(git -C "$repository_path" ls-remote --heads origin "$branch_name") ]]
  then
    git -C "$repository_path" push origin --delete "$branch_name"
  fi
}