name: 'Setup Go'
description: 'Setup Go with caching'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version-file: app/go.mod
        cache: true
        cache-dependency-path: |
          app/go.sum
          e2e-tests/go.sum