name: Setup Go utilities
description: Install and cache golangci-lint and gotestsum.

inputs:
  golangci_lint_version:
    description: The version of golangci-lint to install.
    required: false
    default: "v2.11.4"
  gotestsum_version:
    description: The version of gotestsum to install.
    required: false
    default: "v1.13.0"

runs:
  using: "composite"
  steps:
    - name: Cache golangci-lint
      id: golangci-lint-cache
      uses: actions/cache@v3
      with:
        path: /usr/local/bin/golangci-lint
        key: golangci-lint-${{ inputs.golangci_lint_version }}-${{ runner.os }}

    - name: Install golangci-lint
      if: steps.golangci-lint-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "Installing golangci-lint version: ${{ inputs.golangci_lint_version }}"
        curl -sSfL "https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh" | sh -s -- -b /usr/local/bin "${{ inputs.golangci_lint_version }}"

    - name: Verify golangci-lint Installation
      shell: bash
      run: golangci-lint version

    - name: Cache gotestsum
      id: gotestsum-cache
      uses: actions/cache@v3
      with:
        path: /usr/local/bin/gotestsum
        key: gotestsum-${{ inputs.gotestsum_version }}-${{ runner.os }}

    - name: Install gotestsum
      if: steps.gotestsum-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "Installing gotestsum version: ${{ inputs.gotestsum_version }}"
        GO111MODULE=on go install gotest.tools/gotestsum@${{ inputs.gotestsum_version }}
        sudo mv ~/go/bin/gotestsum /usr/local/bin/

    - name: Verify gotestsum Installation
      shell: bash
      run: gotestsum --version