#!/usr/bin/env bash

bats_load_library "writeTeamFile"
bats_load_library "mrt/execute"

clone_repositories_using_mrt() {
	readarray -t repositoriesUrls < <(getRepositoryUrls "$@")
	clone_repository_urls_using_mrt "${repositoriesUrls[@]}"
}

clone_repository_urls_using_mrt() {
	writeRepositoriesUrls "$@"

	mrtSetupClone
}