#!/usr/bin/env bash

set -e

rootDir=$1
shift

currentOS="$("$rootDir/mrt" run detect-platform --os)"
currentArch="$("$rootDir/mrt" run detect-platform --arch)"

"$rootDir"/mrt run build "$currentOS/$currentArch"
"$rootDir/$("$rootDir" mrt run bin-path)/mrt-$currentOS-$currentArch" "$@"
