#!/usr/bin/env bash

set -e

rootDir="$1"
shift

GITHUB_OWNER="janisZisenisTesting"
TEST_REPO_DIR="$rootDir/test-repos"

if ! gh auth status &> /dev/null; then
    echo "Please log in using 'gh auth login'."
    exit 1
fi

REPOS=$(gh repo list $GITHUB_OWNER --limit 1000 --json nameWithOwner -q '.[] | .nameWithOwner')

[ -z "$REPOS" ] && { echo "No repositories found."; exit 1; }

rm -rf "$TEST_REPO_DIR"

for REPO in $REPOS; do
    REPO=$(echo "$REPO" | tr -d '"')
    TARGET_DIR="$TEST_REPO_DIR/$REPO"
    mkdir -p "$TARGET_DIR"
    gh repo clone "$REPO" "$TARGET_DIR"
done

echo "Cloning completed!"