name: 'Run E2E tests'
description: 'Runs E2E tests on a specified platform'
inputs:
  platform:
    description: 'Platform to run the tests on'
    required: true
  binary-name:
    description: 'Name of the binary'
    required: true
  binary-path:
    description: 'Path to binary'
    required: true
  private-key:
    description: 'Private key for tests'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: ${{ inputs.platform }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - uses: ./.github/actions/setup-mrt
    - name: Download binary
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.binary-name }}
        path: ${{ inputs.binary-path }}
    - name: Make binary executable
      shell: bash
      run: chmod 755 ${{ inputs.binary-path }}/${{ inputs.binary-name }}
    - name: Setup git config
      shell: bash
      run: |
        git config --global user.email "ci@multi-repository-tool.com"
        git config --global user.name "MRT-CI-User"
    - name: Setup ssh
      shell: bash
      run: |
        echo "${{ inputs.private-key }}" > .ssh/private-key
        chmod 400 ./.ssh/private-key
        mkdir -p $HOME/.ssh
        sed "s*WORKSPACE_DIR*$GITHUB_WORKSPACE*g" .ssh/config > $HOME/.ssh/config
        cat $HOME/.ssh/config
    - name: Run E2E Tests
      shell: bash
      run: mrt run docker-tests ${{ inputs.platform }}