name: 'Run E2E tests'
description: 'Runs E2E tests'
inputs:
  binary-name:
    description: 'Name of the binary'
    required: true
  binary-path:
    description: 'Path to binary'
    required: true
  private-key:
    description: 'Private key for tests'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Download binary
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.binary-name }}
        path: ${{ inputs.binary-path }}
    - name: Make binary executable
      shell: bash
      run: chmod 755 ${{ inputs.binary-path }}/${{ inputs.binary-name }}
    - name: Setup ssh
      shell: bash
      run: |
        echo "${{ inputs.private-key }}" > .ssh/private-key
        chmod 400 ./.ssh/private-key
        mkdir -p $HOME/.ssh
        sed "s*WORKSPACE_DIR*$GITHUB_WORKSPACE*g" .ssh/config > $HOME/.ssh/config
        cat $HOME/.ssh/config
    - name: setup git user
      shell: bash
      run: |
        git config --global user.email "testing@testing.com"
        git config --global user.name "TestRunner"
    - uses: ./.github/actions/setup-mrt
    - name: Run E2E Tests
      shell: bash
      run: mrt run e2e-tests