name: 'Run E2E tests'
description: 'Runs E2E tests'
inputs:
  private-key:
    description: 'Private key for tests'
    required: true
runs:
  using: 'composite'      
  steps:
    - uses: ./.github/actions/setup-mrt
    - uses: ./.github/actions/download-binaries
    - name: Setup ssh
      shell: bash
      run: |
        mkdir -p .ssh
        echo "${{ inputs.private-key }}" > .ssh/private-key
        chmod 400 ./.ssh/private-key
    - name: Configure git
      shell: bash
      run: |
        git version
        git config --global user.email "testing@testing.com"
        git config --global user.name "TestRunner"
    - name: Run E2E Tests
      shell: bash
      run: |
        mrt run detect-platform
        mrt run e2e-tests