name: 'Run E2E tests'
description: 'Runs E2E tests'
inputs:
  private-key:
    description: 'Private key for tests'
    required: true
runs:
  using: 'composite'      
  steps:
    - uses: ./.github/actions/setup-mrt
    - uses: ./.github/actions/download-binaries
    - name: Setup ssh
      shell: bash
      run: |
        echo "${{ inputs.private-key }}" > .ssh/private-key
        chmod 400 ./.ssh/private-key
        mkdir -p $HOME/.ssh
        sed "s*WORKSPACE_DIR*$GITHUB_WORKSPACE*g" .ssh/config > $HOME/.ssh/config
        cat $HOME/.ssh/config
    - name: Configure git
      shell: bash
      run: |
        git version
        git config --global core.compression 0
        git config --global user.email "testing@testing.com"
        git config --global user.name "TestRunner"
    - name: Run E2E Tests
      shell: bash
      run: |
        mrt run detect-platform
        mrt run e2e-tests