name: 'Run E2E tests'
description: 'Runs E2E tests'
inputs:
  private-key:
    description: 'Private key for tests'
    required: true
runs:
  using: 'composite'      
  steps:
    - uses: ./.github/actions/setup-mrt
    - name: Set binary variables
      id: binary-variables
      shell: bash
      run: |
        echo "binary-path=$(mrt run binary-location -- --dir)" >> $GITHUB_OUTPUT
        echo "binary-name=$(mrt run binary-location -- --exe-name)" >> $GITHUB_OUTPUT
    - name: Download binary
      uses: actions/download-artifact@v4
      with:
        name: ${{ steps.binary-variables.outputs.binary-name }}
        path: ${{ steps.binary-variables.outputs.binary-path }}
    - name: Make binary executable
      shell: bash
      run: chmod 755 $(mrt run binary-location)
    - name: Setup ssh
      shell: bash
      run: |
        echo "${{ inputs.private-key }}" > .ssh/private-key
        chmod 400 ./.ssh/private-key
        mkdir -p $HOME/.ssh
        sed "s*WORKSPACE_DIR*$GITHUB_WORKSPACE*g" .ssh/config > $HOME/.ssh/config
        cat $HOME/.ssh/config
    - name: setup git user
      shell: bash
      run: |
        git config --global user.email "testing@testing.com"
        git config --global user.name "TestRunner"
    - name: Run E2E Tests
      shell: bash
      run: mrt run e2e-tests