name: Go

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      go-version: '1.23'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ env.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go-version }}
      - name: Install dependencies
        run: |
          cd app
          go get
      - name: Build
        run: |
          cd app
          go build -v
      - name: Test with Go
        run: |
          cd app
          go test -json > TestResults.json
      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: Test-Results
          path: TestResults.json

