name: Run E2E Tests

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  workflow_dispatch: 

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    outputs:
      build-matrix: ${{ steps.set-matrix.outputs.build-matrix }}
      test-matrix: ${{ steps.set-matrix.outputs.test-matrix }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup mrt
        run: | 
          $(pwd)/bin/github/package/setup.sh
          echo "$(pwd)/bin/github" >> $GITHUB_PATH
      - name: Generate matrix
        id: set-matrix
        run: |
          echo "build-matrix=$(mrt run build-matrix)" >> $GITHUB_OUTPUT
          echo "test-matrix=$(mrt run test-matrix)" >> $GITHUB_OUTPUT
  build:
    name: Build for Platform ${{ matrix.platform.name }}
    runs-on: ubuntu-latest
    needs: build-matrix
    strategy:
      matrix: ${{ fromJson(needs.build-matrix.outputs.build-matrix) }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup mrt
        run: | 
          $(pwd)/bin/github/package/setup.sh
          echo "$(pwd)/bin/github" >> $GITHUB_PATH
      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v5
        with:
          go-version-file: app/go.mod
      - name: Build binary
        run: |
          command="mrt run build -- --commit-sha ${{ github.sha }} ${{ matrix.platform.name }}"
          if [[ ${{ github.ref }} == 'refs/tags/' ]]
          then
            command+=" --semver ${{ github.ref_name }}"
          fi
          $command
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.binary-name }}
          path: ${{ matrix.platform.binary-path }}
          retention-days: 7        
  run-tests:
    name: Run tests for platform ${{ matrix.platform.name }}
    runs-on: ubuntu-latest
    needs: [build, build-matrix]
    strategy:
      matrix: ${{ fromJson(needs.build-matrix.outputs.test-matrix) }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ matrix.platform.name }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Setup mrt
        run: |
          $(pwd)/bin/github/package/setup.sh
          echo "$(pwd)/bin/github" >> $GITHUB_PATH
      - name: Download binary
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.platform.binary-name }}
          path: ${{ matrix.platform.binary-path }}
      - name: Make binary executable
        run: chmod 755 ${{ matrix.platform.binary-path }}/${{ matrix.platform.binary-name }}
      - name: Setup git config
        run: |
          git config --global user.email "ci@multi-repository-tool.com"
          git config --global user.name "MRT-CI-User"
      - name: Setup ssh
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > .ssh/private-key
          chmod 400 ./.ssh/private-key
          mkdir -p $HOME/.ssh
          sed "s*WORKSPACE_DIR*$GITHUB_WORKSPACE*g" .ssh/config > $HOME/.ssh/config
          cat $HOME/.ssh/config
      - name: Run E2E Tests
        run: |
          /usr/bin/env bash --version
          mrt run docker-tests ${{ matrix.platform.name }}
  create-release:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs: run-tests
    outputs:
      upload-url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }}
          body: ""
          draft: false
          prerelease: false
  upload-binaries:
    name: Upload binaries for ${{ matrix.platform.name }}
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs: [create-release, build-matrix]
    strategy:
      matrix: ${{ fromJson(needs.build-matrix.outputs.build-matrix) }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup mrt
        run: | 
          $(pwd)/bin/github/package/setup.sh
          echo "$(pwd)/bin/github" >> $GITHUB_PATH
      - name: Download binary
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.platform.binary-name }}
          path: ${{ matrix.platform.binary-path }}
      - name: Make binary executable
        run: chmod 755 ${{ matrix.platform.binary-path }}/${{ matrix.platform.binary-name }}
      - name: Upload binaries
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload-url }}
          asset_path: ${{ matrix.platform.binary-path }}/${{ matrix.platform.binary-name }}
          asset_name: ${{ matrix.platform.binary-name }}
          asset_content_type: application/octet-stream
  