name: Run E2E Tests

on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      go-version: '1.23'
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Setup Go ${{ env.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go-version }}
      - name: Setup ssh
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > .ssh/private-key
          chmod 400 ./.ssh/private-key
          mkdir -p $HOME/.ssh
          sed "s*WORKSPACE_DIR*$GITHUB_WORKSPACE*g" .ssh/config > $HOME/.ssh/config
          cat $HOME/.ssh/config
      - name: Run E2E Tests
        run: |
          ./do run-e2e-tests