name: Run E2E Tests

on: push

env:
  binaries-path: "build/bin"
  binaries-name: "binaries"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      go-version: '1.23'
    steps:
      - uses: actions/checkout@v4
      - name: Setup mrt
        run: ./mrt-multiplatform/setup.sh
      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v5
        with:
          go-version: ${{ env.go-version }}
          go-version-file: app/go.mod
      - name: Build binaries
        run: |
          ./mrt-multiplatform/setup.sh
          ./mrt run build
      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.binaries-name }}
          path: ${{ env.binaries-path }}
          retention-days: 7
  run-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.binaries-name }}
          path: ${{ env.binaries-path }}
      - name: Setup mrt
        run: ./mrt-multiplatform/setup.sh
      - name: Make binaries executable
        run: chmod +x ${{ env.binaries-path}}/${{ env.binaries-name}}
      - name: Setup git config
        run: |
          git config --global user.email "ci@multi-repository-tool.com"
          git config --global user.name "MRT-CI-User"
      - name: Setup ssh
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > .ssh/private-key
          chmod 400 ./.ssh/private-key
          mkdir -p $HOME/.ssh
          sed "s*WORKSPACE_DIR*$GITHUB_WORKSPACE*g" .ssh/config > $HOME/.ssh/config
          cat $HOME/.ssh/config
      - name: Run E2E Tests
        run: ./mrt run e2e-tests